### ISSUE TITLE
TypeError: as_dict() got an unexpected keyword argument 'depth'

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/Utils-Flask-SQLAlchemy#9]
Sur une installation fraîche de GeoNature 2.3.2, avec python 3.6.9. Une erreur est soulevée lors de l'appel des stats générales.

```
Exception on /synthese/general_stats [GET]
Traceback (most recent call last):
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fcloitre/geonature/backend/geonature/core/gn_permissions/decorators.py", line 98, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/utils_flask_sqla/response.py", line 18, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/fcloitre/geonature/backend/geonature/core/gn_synthese/routes.py", line 648, in general_stats
    allowed_datasets = get_datasets_cruved(info_role)
  File "/home/fcloitre/geonature/backend/geonature/core/gn_meta/repositories.py", line 86, in get_datasets_cruved
    return [d.as_dict(True) for d in data]
  File "/home/fcloitre/geonature/backend/geonature/core/gn_meta/repositories.py", line 86, in <listcomp>
    return [d.as_dict(True) for d in data]
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/utils_flask_sqla/serializers.py", line 125, in serializefn
    for x in getattr(self, rel)
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/utils_flask_sqla/serializers.py", line 125, in <listcomp>
    for x in getattr(self, rel)
  File "/home/fcloitre/geonature/backend/venv/lib/python3.6/site-packages/utils_flask_sqla/serializers.py", line 129, in serializefn
    recursif=recursif, depth=depth, relationships=relationships)
TypeError: as_dict() got an unexpected keyword argument 'depth'
```

**Comment by lpofredc** [comment]
Lié à la PR #6 ?

**Comment by lpofredc** [comment]
#6

**Comment by lpofredc** [comment]
Un `pip install -r requirements.txt` sur l'installation geonature a résolu le pb...
